---
name: sudo-touchid
description: Sudo Touch ID project
slack: airsupport-goalie
email: support@airbnb.com
teams:
- one_airbnb_team_id_1510
data_sensitivity: public
additional_owners: 
  - victor_desouza
type: library
primary_language: golang
